models/forms.py
#!/usr/bin/python3
"""
forms module
"""
from flask_wtf import FlaskForm
from models.user import User
from wtforms import StringField, PasswordField, SubmitField, BooleanField, FieldList
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError


class Register(FlaskForm):
    """
    New member registration class/form
    """
    fullname = StringField(
        "Full Name",
        validators=[
            DataRequired(),
            Length(min=5, max=50)
        ]
    )

    email = StringField(
        "Email",
        validators=[
            DataRequired(),
            Email()
        ]
    )

    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            Length(min=6, max=50)
        ]
    )

    confirm_password = PasswordField(
        "Confirm Password",
        validators=[
            DataRequired(),
            EqualTo("password")
        ]
    )

    submit = SubmitField("Register")


    def validate_email(self, email):
        """
        checks if the email already exists in the database
        """
        existing_email = User.query.filter_by(email=email.data).first()
        if existing_email:
            raise ValidationError("This email already has an account associated with it")


class LogIn(FlaskForm):
    """
    Existing member log in class/form
    """
    email = StringField(
        "Email",
        validators=[
            DataRequired(),
            Email()
        ]
    )

    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            Length(min=6, max=50)
        ]
    )

    remember = BooleanField("Remember Me")

    submit = SubmitField("Log In")


class NewRecipe(FlaskForm):
    """A new recipe class/form"""
    title =  StringField(
        "Recipe Name",
        validators=[DataRequired()],
    )

    ingredients = FieldList(
        StringField(
            "Ingredient",
            validators=[DataRequired()],
        ),
        min_entries=1,
    )

    instructions = FieldList(
        StringField(
            "Instruction",
            validators=[DataRequired()],
        ),
        min_entries=1,
    )

    submit = SubmitField("Post New Recipe")


class RequestPasswordReset(FlaskForm):
    email = StringField(
        "Email",
        validators=[
            DataRequired(),
            Email()
        ]
    )

    submit = SubmitField("Request Password Reset")

    def validate_email(self, email):
        """
        checks if the email already exists in the database
        """
        existing_email = User.query.filter_by(email=email.data).first()
        if existing_email is None:
            raise ValidationError("This email is not associated with an account. Please register")


class ResetPassword(FlaskForm):
    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            Length(min=6, max=50)
        ]
    )

    confirm_password = PasswordField(
        "Confirm Password",
        validators=[
            DataRequired(),
            EqualTo("password")
        ]
    )

    submit = SubmitField("Reset Password")

models/main/forms.py
#!/usr/bin/python3

models/__init__.py
#!/usr/bin/python3
"""initialises the app"""

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from models.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()


def create_app(config=Config):
    """creates an instance of the app"""
    app = Flask(__name__)
    app.config.from_object(Config)
    app.url_map.strict_slashes = False

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from models.users.user_routes import users
    from models.recipes.recipe_routes import recipes
    from models.main.routes import main
    from models.errors.error_handler import errors

    app.register_blueprint(users)
    app.register_blueprint(recipes)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

models/main/routes.py
#!/usr/bin/python3
from flask import Blueprint, render_template, request
from models.recipe import Recipe

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
    """handles the about route"""
    return render_template("home_page.html")


@main.route("/recipes")
def recipes():
    """handles the home route"""
    recipes = Recipe.query.order_by(Recipe.date_posted.desc()).all()
    return render_template("recipes.html", posts=recipes)


@main.route("/search")
def search():
    """search functionality route"""
    search_term = request.args.get("search")

    recipes = Recipe.query.filter(Recipe.title.ilike(f"%{search_term}%")).all()
    return render_template("search_results.html", title="Search Results", recipes=recipes)

models/templates/account.html
{% extends "layout_template.html" %}
{% block content %}
<div class="content-section">
	<div class="media">
		<img class="rounded-circle account-img" src="{{ profile_pic }}">
		<div class="media-body">
			<h2 class="account-heading">{{ current_user.fullname }}</h2>
			<p class="text-secondary">{{ current_user.email }}</p>
		</div>
	</div>
	<div id="formContainer" style="display: none;">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account Info</legend>
	
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}
	
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label()}} <br>
					{{ form.picture(class="form-control-file custom-btn")}}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span> <br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mt-2">
				{{ form.submit(class="btn btn-outline-secondary")}}
			</div>
		</form>
	</div>
	<div class="form-group mt-2" id="buttonContainer">
		<button class="btn btn-outline-secondary" onclick="showForm()">Update Info</button>
	</div>
</div>
{% if posts %}
	{% for post in posts %}
		<article class="media content-section">
			<div class="media-body">
				<h2>{{ post.title }}</h2>
				{% if post.recipe_pic %}
					<img class="recipe-img" src="{{ url_for('static', filename='images/recipe_pics/' + post.recipe_pic) }}">
				{% endif %}

				<div class="article-metadata">
					<small class="text-muted">Posted on {{ post.formatted_date }}</small>

					{% if current_user == post.user %}
					<div>
						<a class="btn btn-secondary custom-btn m-1" href="{{ url_for('recipes.update_recipe', recipe_id=post.id) }}">Update</a>
						<button type="button" class="btn btn-danger custom-btn m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
					</div>

					<!-- Modal -->
					<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
								<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<p>Delete {{ post.title }} recipe?</p>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
								<form action="{{ url_for('recipes.delete_recipe', recipe_id=post.id) }}" method="POST">
									<input class="btn btn-danger" type="submit" value="Delete">
								</form>
							</div>
							</div>
						</div>
					</div>
				{% endif %}
				</div>

				<p>
					<h3>Ingredients</h3>
					{% for item in post.ingredients %}
						<li>{{ item }}</li>
					{% endfor %}
					<br>
					<h3>Instructions</h3>
					<ol>
						{% for step in post.instructions %}
							{% if step %}
								<li>{{ step }}</li>
							{% endif %}
						{% endfor %}
					</ol>
				</p>
			</div>
		</article>
	{% endfor %}
{% else %}
	<p class="article-metadata">
		You have not posted any recipies <a href="{{ url_for('recipes.new_recipe') }}">Post a recipe</a>
	</p>
{% endif %}
{% endblock content %}

models/templates/home_page.html
{% extends "layout_template.html" %}
{% block content %}
<div class="homepage-container">
	<section class="homepage">
		<div class="overlay">
			<p style="font-size: 75px;">Kenyan Dishes</p>
		</div>
	</section>
	
	<div class="header-container">
		<h1>Explore the rich flavors of Kenyan cuisine</h1>

		<p  style="font-size: larger;">Welcome to our culinary hub, where Kenyan and African cuisine comes alive. We celebrate diverse cultures and traditions through our recipes, from the savory Nyama Choma and Ugali to the tangy Sour Milk. Whether you're a seasoned chef or a culinary novice, we've got something for everyone. Share your own recipes, discover new ones, and let's create a global community of food lovers who appreciate the richness and diversity of African cuisine. So, are you ready for this culinary adventure?</p>
		
		<button class="btn btn-outline-secondary"><a href="{{ url_for('main.recipes') }}"> Let's get cooking!</a></button>
	</div>	

	<section class="features">
		<div class="feature">
			<div id="carouselExample" class="carousel slide mb-4" data-bs-ride="carousel" data-interval="10" style="width: 40%; height: 400px;">
				<div class="carousel-inner">
					{% for i in range(5) %}
						<div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
							<img src="{{ url_for('static', filename='images/carousel/food_' + i|string + '.jpg') }}" alt="">
						</div>
					{% endfor %}
				</div>
			</div>

			<div class="content">
				<h2>Recipe Collection</h2>
				<p><a href="{{ url_for('main.recipes') }}">Browse</a> a variety of Kenyan recipes with step-by-step instructions.</p>
			</div>
		</div>
		<div class="feature">
			<div class="content">
				<h2>User Accounts</h2>
				<p><a href="{{ url_for('users.register') }}">Create an account</a> to add and share your own favorite recipes.</p>
			</div>
			<img src="{{ url_for('static', filename='images/features/user_accounts.jpeg') }}" alt="">
		</div>
		<div class="feature">
			<img src="{{ url_for('static', filename='images/features/community_interactions.jpg') }}" alt="">
			<div class="content">
				<h2>Community Interaction</h2>
				<p>Connect with other food enthusiasts, share tips, and discuss Kenyan and African cuisine.</p>
			</div>
		</div>
	</section>

	<section class="about">
		<div class="container">
			<h2>About Kenyan Dishes</h2>
			
			<p>Welcome to <a href="{{ url_for('main.home') }}" target="_blank">Kenyan Dishes</a>, where culinary passion meets a celebration of Kenyan and African flavors! My journey began with the realization that the rich tapestry of regional dishes in Kenya and Africa as a whole deserved a global stage. <a href="{{ url_for('main.home') }}" target="_blank">Kenyan Dishes</a> is not just a project; it's a personal mission to bridge culinary borders. I noticed a gap in accessible food knowledge, inspiring me to create a space where every corner of Kenya and Africa can share their unique recipes effortlessly. As a Portfolio Project for <a href="https://www.alxafrica.com/" target="_blank">ALX Africa's</a> Software Engineering program, <a href="{{ url_for('main.home') }}" target="_blank">Kenyan Dishes</a> is more than a website; it's a tribute to innovation, growth, and community building. Join us in turning every meal into a shared memory and savoring the taste of unity, one recipe at a time!</p>
			
			<h1>Contacts</h1>
			<ul class="team">
				<li><a href="https://www.linkedin.com/in/wanjang-i-gituku-81410572/" target="_blank"><img src="{{ url_for('static', filename='images/icons/linkedin.png') }}" alt=""></a></li>
				<li><a href="https://github.com/Ras-Pekt" target="_blank"><img src="{{ url_for('static', filename='images/icons/github.png') }}" alt=""></a></li>
				<li><a href="https://twitter.com/WanjangiG" target="_blank"><img src="{{ url_for('static', filename='images/icons/twitter.png') }}" alt=""></a></li>
				<li><a href="mailto:wanjangi.gituku@gmail.com" target="_blank"><img src="{{ url_for('static', filename='images/icons/gmail.png') }}" alt=""></a></li>
			</ul>
			<p>Find the project on GitHub: <a href="https://github.com/Ras-Pekt/Kenyan_Dishes" target="_blank">Kenyan Dishes Repository</a></p>
		</div>
	</section>
</div>
{% endblock content %}

models/templates/layout_template.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">
	<link rel="icon" href="{{ url_for('static', filename='images/icons/favicon.ico') }}" type="image/x-icon">
	
	{% if title %}
		<title>Kenyan Dishes - {{ title }}</title>
	{% else %}
		<title>Kenyan Dishes</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container d-flex justify-content-between">
				<div>
					<a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Kenyan Dishes</a>
					<a class="navbar-brand mr-4" href="{{ url_for('main.recipes') }}">Recipes</a>
				</div>
				<div>
					<button class="navbar-toggler fixed-button" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarToggle">
						<div class="navbar-nav">
							<form class="d-flex" role="search" action="{{ url_for('main.search') }}" method="GET">
								<input class="form-control me-2" type="search" name="search" id="searchBox" placeholder="Search" aria-label="Search">
								<button class="btn btn-outline-secondary" type="submit" id="searchButton">Search</button>
							</form>
							{% if current_user.is_authenticated %}
								<a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.fullname }}</a>
								<a class="nav-item nav-link" href="{{ url_for('recipes.new_recipe') }}">New Recipe</a>
								<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
							{% else %}
								<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
								<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>

	<main role="main" class="container-fluid">
	<div class="row">
		<div class="grid">
			{% with messages  = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category_value, message in messages %}
						<div class="alert alert-{{ category_value }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			{% block content %}{% endblock %}
		</div>
	</div>
	</main>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	<script src="{{ url_for('static', filename='scripts/scripts.js') }}"></script>
</body>
</html>

models/templates/login.html
{% extends "layout_template.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group mt-2 mb-2">
				{{ form.submit(class="btn btn-outline-secondary btn-sm")}}
			</div>
			<small class="text-muted">
				<a href="{{ url_for('users.request_password_reset') }}">Forgot Password?</a>
			</small>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Don't have an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
		</small>
	</div>
{% endblock content %}

models/templates/new_recipe.html
{% extends "layout_template.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>

				<div class="form-group">
					{{ form.title.label(class="form-control-label")}}

					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>

				<div class="form-group mt-2" id="ingredients-container">
					{{ form.ingredients.label(class="form-control-label")}}
				
					{% if form.ingredients.errors %}
						{{ form.ingredients(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.ingredients.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{% for ingredient in form.ingredients %}
							{{ ingredient(class="form-control form-control-md mb-2") }}
						{% endfor %}
					{% endif %}
				</div>
				<button class="btn btn-outline-secondary mt-2" type="button" id="add-ingredient">Add Another Ingredient</button>

				<div class="form-group mt-2" id="instructions-container">
					{{ form.instructions.label(class="form-control-label")}}
				
					{% if form.instructions.errors %}
						{{ form.ingredients(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.instructions.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{% for instruction in form.instructions %}
							{{ instruction(class="form-control form-control-md mb-2") }}
						{% endfor %}
					{% endif %}
				</div>
				<button class="btn btn-outline-secondary mt-2" type="button" id="add-instruction">Add Another Instruction</button>
				<div class="form-group mt-2">
					{{ form.picture.label()}} <br>
					{{ form.picture(class="form-control-file custom-btn")}}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span> <br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mt-2">
				{{ form.submit(class="btn btn-outline-secondary")}}
			</div>
		</form>
	</div>
{% endblock content %}

models/templates/recipe.html
{% extends "layout_template.html" %}
{% block content %}
	<article class="media content-section">
		<div class="media-body">
			<h2 class="article-title">{{ recipe.title }}</h2>
			{% if recipe.recipe_pic %}
				<img class="recipe-img" src="{{ url_for('static', filename='images/recipe_pics/' + recipe.recipe_pic) }}">
			{% endif %}

			<div class="article-metadata">
				Posted by <a class="mr-2" href="{{ url_for('users.user', user_id=recipe.user_id) }}">{{ recipe.user.fullname }}</a> on 
				<small class="text-muted">{{ recipe.formatted_date }}</small>

				{% if current_user == recipe.user %}
					<div>
						<a class="btn btn-secondary custom-btn m-1" href="{{ url_for('recipes.update_recipe', recipe_id=recipe.id) }}">Update</a>
						<button type="button" class="btn btn-danger custom-btn m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
					</div>

					<!-- Modal -->
					<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
								<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<p>Delete {{ recipe.title }} recipe?</p>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
								<form action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" method="POST">
									<input class="btn btn-danger" type="submit" value="Delete">
								</form>
							</div>
							</div>
						</div>
					</div>
				{% endif %}
			</div>
			
			<p>
				<h3>Ingredients</h3>
				{% for item in recipe.ingredients %}
					<li>{{ item }}</li>
				{% endfor %}
				<br>
				<h3>Instructions</h3>
				<ol>
					{% for step in recipe.instructions %}
						{% if step %}
							<li>{{ step }}</li>
						{% endif %}
					{% endfor %}
				</ol>
			</p>
		</div>
	</article>
	
{% endblock content %}

models/templates/recipes.html
{% extends "layout_template.html" %}
{% block content %}
<div class="homepage-container">
	<section class="homepage">
		<div class="overlay">
			<h1>Kenyan Dishes</h1>
			<p style="font-size: xx-large; color: goldenrod;">Where Kenyan and African cuisine comes alive!</p>
		</div>
	</section>

	<div class="recipe-grid">
		{% for post in posts %}
			<div class="recipe-card">
				<h2><a href="{{ url_for('recipes.recipe', recipe_id=post.id) }}">{{ post.title }}</a></h2>
				{% if post.recipe_pic %}
				<a href="{{ url_for('recipes.recipe', recipe_id=post.id) }}"><img class="recipe-img" src="{{ url_for('static', filename='images/recipe_pics/' + post.recipe_pic) }}"></a>
				{% endif %}


				<div class="article-metadata">
					Posted by <a class="mr-2" href="{{ url_for('users.user', user_id=post.user_id) }}">{{ post.user.fullname }}</a> on 
					<small class="text-muted">{{ post.formatted_date }}</small>
				</div>
			</div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

models/templates/register.html
{% extends "layout_template.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Register</legend>
				<div class="form-group">
					{{ form.fullname.label(class="form-control-label")}}

					{% if form.fullname.errors %}
						{{ form.fullname(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.fullname.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.fullname(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label")}}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mt-2">
				{{ form.submit(class="btn btn-outline-secondary")}}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
		</small>
	</div>
{% endblock content %}

models/templates/request_password_reset.html
{% extends "layout_template.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Request Password Reset</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-md mb-2 is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-md mb-2")}}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group mt-2 mb-2">
				{{ form.submit(class="btn btn-outline-secondary btn-sm")}}
			</div>
		</form>
	</div>
{% endblock content %}